# -*- coding: utf-8 -*-
"""HermesBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9nfd4x-zlQdz04Oc3SIQ1z6xwRbkSLE
"""

# !pip install pyTelegramBotAPI

"""importar paquete principal"""

from config import *
import telebot

# HermesBot
bot = telebot.TeleBot(TELEGRAM_TOKEN)

# responde al comando /start
@bot.message_handler(commands=['start'])
def cmd_start(message):
  '''
  Da la bienvenida al bot
  '''
  bot.reply_to(message, "¡Hola! ¿Como estas?")

# responde al comando /help
@bot.message_handler(commands=['help'])
def cmd_help(message):
  '''
  Pregunta en que puede ayudar
  '''
  bot.reply_to(message, "¿En que te puedo ayudar?")

# responde al comando /imagen
@bot.message_handler(commands=['imagen'])
def cmd_send_imagen(message):
  '''
  Envia una foto
  '''
  foto = open('Buho_Luna.jpg', 'rb')
  bot.send_photo(message.chat.id, foto, "Buho Luna!")

# responde al comando /pdf
@bot.message_handler(commands=['pdf'])
def cmd_send_pdf(message):
  '''
  Envia una foto
  '''
  archivo = open('9. Noveno grado.pdf', 'rb')
  bot.send_document(message.chat.id, archivo, "Buho Luna!")

# responde al comando /pdf
@bot.message_handler(commands=['audio'])
def cmd_send_audio(message):
  '''
  Envia una foto
  '''
  audio = open('audio.mp3', 'rb')
  bot.send_audio (message.chat.id, audio, "vivaldi")

# responde a mensajes de texto
@bot.message_handler(content_types=["text"])
def bot_mensajes_texto(message):
  '''
  Gestiona los mensajes recibidos
  '''
  texto_md  = '*__FORMATOS MARKDOWN__*\n'
  texto_md += '*NEGRITA*\n'
  texto_md += '_CURSIVA_\n'
  texto_md += '__SUBRAYADO__\n'
  texto_md += '~TACHADO~\n'
  texto_md += '```MONOESPACIADO```\n'
  texto_md += '||SPOILER||\n'
  texto_md += '[ENLACE](https://beacons.ai/hermesvillarreal)\n'
  if message.text.startswith('/'):
    bot.send_message(message.chat.id, 'Comando no disponible')
  else:
    bot.send_message(message.chat.id, texto_md, parse_mode='MarkDownV2', disable_web_page_preview=True)


## MAIN ###
#if __name__ == '__name__':
print('Iniciando el bot')
bot.polling()
print('Termiando el bot')